### ISSUE TITLE
REST API versions are unnecessary for Electron

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime-studio#24]
Since we are moving to an Electron-based app, we don't need to worry about versioning the API anymore, which will simplify the handshake code quite a bit.

**Comment by ebolyen** [comment]
I can get started on this, and re-factoring some of the HMAC logic to be http method independent. (Something like `secure_api_fetch`.)

**Comment by jakereps** [comment]
That last push fixed this. 💥
