### ISSUE TITLE
Run a job

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime-studio#29]
We need to attach `Go` to an `Executor` in the QIIME SDK so that work can be done by the interface.

This will need to be non-blocking, so we can either get the WSGI server to spawn a new flask process for each request OR, set up a non-blocking process call that we can poll periodically OR, we could create something like SSE to actually push the notification to the interface.

**Comment by jakereps** [comment]
Is there any preference over setting up: 

1. A unique ID for each job that is returned by the JSON response from the request to start the job, tracking it in a global job dict, and checking the statuses of running jobs from the UI, say every second or whatever, until there are no more running jobs.

2. Adding a callback to the `Future` that handles the server response letting the fetch and promises do their thing and just hang out waiting for it? Fetch is async, and it seems there is no timeout if you don't set one for fetch, promises, or our WSGI server. (unsure if this second one works or not, if Flask needs the endpoint hit to return before it allows any others to run, or if it'd even pass the JSON on to the response or if you'd have to do like a `yield from callback` or something, I'd have to test it out)

```python
@v1.route(...)
def execute_job(..):
    ...
    def callback(process):
        return jsonify(process.result().returncode) # or whatever...
    process = SUBPROCESS_EXECUTOR(...)
    process.add_done_callback(callback)
    # end of function/endpoint, so no return until finish leaving the request open
```
