### ISSUE TITLE
Create Actions

### ISSUE THREAD

**Issue by jakereps** [qiime2/qiime-studio#4]
- [x] NEW_ARTIFACT
- [ ] EXPECTING_ARTIFACT
- [x] DELETE_ARTIFACT
- [x] REFRESH_ARTIFACTS

- [x] LOAD_PLUGINS
- [x] LOAD_WORKFLOWS

- [ ] CREATE_JOB
- [x] START_JOB

**Comment by jakereps** [comment]
These all "exist" now, but probably going to wait until they actually interact with the API and do what they should do before marking them complete.

**Comment by ebolyen** [comment]
This has essentially been handled. The app now has full functionality.
