### ISSUE TITLE
Convert plugin/workflow listing pane to an accordion grouped by plugin

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime-studio#48]
Examples can be seen [here](http://www.w3schools.com/bootstrap/bootstrap_collapse.asp). Basically the goal is to keep the length of this pane under control. We'll need something more robust in the future, but this should work fine for the alpha release.

**Comment by ebolyen** [comment]
@Kleptobismol can you work on this?

**Comment by Kleptobismol** [comment]
@ebolyen sure!
