### ISSUE TITLE
Centralize store to main.js and create IPC dispatch middleware

### ISSUE THREAD

**Issue by ebolyen** [qiime2/qiime-studio#50]
This would be like the `react-router` middleware, expect instead of pages, it would handle open windows. This way there is a single store for the app and each render process is a view of some section of the shared store.

**Comment by ebolyen** [comment]
[samiskin/redux-electron-store](https://github.com/samiskin/redux-electron-store)!!!

**Comment by jakereps** [comment]
Working on this now, as running the visualizers in a separate window without this will require basically passing the entire store over anyways, as it needs the secret key, uris, known types for dropdowns, current artifacts, and basically everything that adding this would easily handle.
