### ISSUE TITLE
support default parameter values

### ISSUE THREAD

**Issue by jairideout** [qiime2/qiime-studio#79]
The framework and CLI now support default values for parameters (https://github.com/qiime2/qiime2/pull/125, https://github.com/qiime2/q2cli/pull/54). It would be great to support default values in the studio.

**Comment by jakereps** [comment]
Can get this going tomorrow. Should require almost no changes, just passing along the defaults with the action signature, and a logic check on the UI side. 👍

**Comment by jairideout** [comment]
Excellent, thanks @jakereps!
